package com.android.memefish.langinfogather.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.android.memefish.langinfogather.db.Picture;
import com.android.memefish.langinfogather.db.Obligee;

import com.android.memefish.langinfogather.db.PictureDao;
import com.android.memefish.langinfogather.db.ObligeeDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig pictureDaoConfig;
    private final DaoConfig obligeeDaoConfig;

    private final PictureDao pictureDao;
    private final ObligeeDao obligeeDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        pictureDaoConfig = daoConfigMap.get(PictureDao.class).clone();
        pictureDaoConfig.initIdentityScope(type);

        obligeeDaoConfig = daoConfigMap.get(ObligeeDao.class).clone();
        obligeeDaoConfig.initIdentityScope(type);

        pictureDao = new PictureDao(pictureDaoConfig, this);
        obligeeDao = new ObligeeDao(obligeeDaoConfig, this);

        registerDao(Picture.class, pictureDao);
        registerDao(Obligee.class, obligeeDao);
    }
    
    public void clear() {
        pictureDaoConfig.clearIdentityScope();
        obligeeDaoConfig.clearIdentityScope();
    }

    public PictureDao getPictureDao() {
        return pictureDao;
    }

    public ObligeeDao getObligeeDao() {
        return obligeeDao;
    }

}
