package com.android.memefish.langinfogather.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.android.memefish.langinfogather.db.Picture;

import com.android.memefish.langinfogather.db.PictureDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig pictureDaoConfig;

    private final PictureDao pictureDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        pictureDaoConfig = daoConfigMap.get(PictureDao.class).clone();
        pictureDaoConfig.initIdentityScope(type);

        pictureDao = new PictureDao(pictureDaoConfig, this);

        registerDao(Picture.class, pictureDao);
    }
    
    public void clear() {
        pictureDaoConfig.clearIdentityScope();
    }

    public PictureDao getPictureDao() {
        return pictureDao;
    }

}
